// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Monopoly.Schema
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct AnnounceRecievedChancePayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static AnnounceRecievedChancePayload GetRootAsAnnounceRecievedChancePayload(ByteBuffer _bb) { return GetRootAsAnnounceRecievedChancePayload(_bb, new AnnounceRecievedChancePayload()); }
  public static AnnounceRecievedChancePayload GetRootAsAnnounceRecievedChancePayload(ByteBuffer _bb, AnnounceRecievedChancePayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AnnounceRecievedChancePayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Player { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPlayerBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetPlayerBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetPlayerArray() { return __p.__vector_as_array<byte>(4); }
  public Monopoly.Schema.Chance? Chance { get { int o = __p.__offset(6); return o != 0 ? (Monopoly.Schema.Chance?)(new Monopoly.Schema.Chance()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Monopoly.Schema.AnnounceRecievedChancePayload> CreateAnnounceRecievedChancePayload(FlatBufferBuilder builder,
      StringOffset playerOffset = default(StringOffset),
      Offset<Monopoly.Schema.Chance> chanceOffset = default(Offset<Monopoly.Schema.Chance>)) {
    builder.StartTable(2);
    AnnounceRecievedChancePayload.AddChance(builder, chanceOffset);
    AnnounceRecievedChancePayload.AddPlayer(builder, playerOffset);
    return AnnounceRecievedChancePayload.EndAnnounceRecievedChancePayload(builder);
  }

  public static void StartAnnounceRecievedChancePayload(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPlayer(FlatBufferBuilder builder, StringOffset playerOffset) { builder.AddOffset(0, playerOffset.Value, 0); }
  public static void AddChance(FlatBufferBuilder builder, Offset<Monopoly.Schema.Chance> chanceOffset) { builder.AddOffset(1, chanceOffset.Value, 0); }
  public static Offset<Monopoly.Schema.AnnounceRecievedChancePayload> EndAnnounceRecievedChancePayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Monopoly.Schema.AnnounceRecievedChancePayload>(o);
  }
};


}
