// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Monopoly.Schema
{

public enum CollectibleType : int
{
  UNSPECIFIED = 0,
  GET_OUT_OF_JAIL_FREE = 1,
};


}
