// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Monopoly.Schema
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DiceDownExtra : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static DiceDownExtra GetRootAsDiceDownExtra(ByteBuffer _bb) { return GetRootAsDiceDownExtra(_bb, new DiceDownExtra()); }
  public static DiceDownExtra GetRootAsDiceDownExtra(ByteBuffer _bb, DiceDownExtra obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DiceDownExtra __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Steps { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Monopoly.Schema.GamePlayer? Player { get { int o = __p.__offset(6); return o != 0 ? (Monopoly.Schema.GamePlayer?)(new Monopoly.Schema.GamePlayer()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Monopoly.Schema.DiceDownExtra> CreateDiceDownExtra(FlatBufferBuilder builder,
      int steps = 0,
      Offset<Monopoly.Schema.GamePlayer> playerOffset = default(Offset<Monopoly.Schema.GamePlayer>)) {
    builder.StartTable(2);
    DiceDownExtra.AddPlayer(builder, playerOffset);
    DiceDownExtra.AddSteps(builder, steps);
    return DiceDownExtra.EndDiceDownExtra(builder);
  }

  public static void StartDiceDownExtra(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSteps(FlatBufferBuilder builder, int steps) { builder.AddInt(0, steps, 0); }
  public static void AddPlayer(FlatBufferBuilder builder, Offset<Monopoly.Schema.GamePlayer> playerOffset) { builder.AddOffset(1, playerOffset.Value, 0); }
  public static Offset<Monopoly.Schema.DiceDownExtra> EndDiceDownExtra(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Monopoly.Schema.DiceDownExtra>(o);
  }
};


}
