// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Monopoly.Schema
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TileEffect : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static TileEffect GetRootAsTileEffect(ByteBuffer _bb) { return GetRootAsTileEffect(_bb, new TileEffect()); }
  public static TileEffect GetRootAsTileEffect(ByteBuffer _bb, TileEffect obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TileEffect __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Monopoly.Schema.TileEffectDisplay? Display { get { int o = __p.__offset(4); return o != 0 ? (Monopoly.Schema.TileEffectDisplay?)(new Monopoly.Schema.TileEffectDisplay()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Monopoly.Schema.TileEffectTiming Timing { get { int o = __p.__offset(6); return o != 0 ? (Monopoly.Schema.TileEffectTiming)__p.bb.GetInt(o + __p.bb_pos) : Monopoly.Schema.TileEffectTiming.UNSPECIFIED; } }
  public Monopoly.Schema.TileEffectExtra ExtraType { get { int o = __p.__offset(8); return o != 0 ? (Monopoly.Schema.TileEffectExtra)__p.bb.Get(o + __p.bb_pos) : Monopoly.Schema.TileEffectExtra.NONE; } }
  public TTable? Extra<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(10); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public Monopoly.Schema.MoveToTileExtra ExtraAsMonopoly_Schema_MoveToTileExtra() { return Extra<Monopoly.Schema.MoveToTileExtra>().Value; }
  public Monopoly.Schema.MoneyExchangeExtra ExtraAsMonopoly_Schema_MoneyExchangeExtra() { return Extra<Monopoly.Schema.MoneyExchangeExtra>().Value; }
  public Monopoly.Schema.MoveStepsExtra ExtraAsMonopoly_Schema_MoveStepsExtra() { return Extra<Monopoly.Schema.MoveStepsExtra>().Value; }
  public Monopoly.Schema.CollectibleExtra ExtraAsMonopoly_Schema_CollectibleExtra() { return Extra<Monopoly.Schema.CollectibleExtra>().Value; }
  public Monopoly.Schema.DetainedExtra ExtraAsMonopoly_Schema_DetainedExtra() { return Extra<Monopoly.Schema.DetainedExtra>().Value; }

  public static Offset<Monopoly.Schema.TileEffect> CreateTileEffect(FlatBufferBuilder builder,
      Offset<Monopoly.Schema.TileEffectDisplay> displayOffset = default(Offset<Monopoly.Schema.TileEffectDisplay>),
      Monopoly.Schema.TileEffectTiming timing = Monopoly.Schema.TileEffectTiming.UNSPECIFIED,
      Monopoly.Schema.TileEffectExtra extra_type = Monopoly.Schema.TileEffectExtra.NONE,
      int extraOffset = 0) {
    builder.StartTable(4);
    TileEffect.AddExtra(builder, extraOffset);
    TileEffect.AddTiming(builder, timing);
    TileEffect.AddDisplay(builder, displayOffset);
    TileEffect.AddExtraType(builder, extra_type);
    return TileEffect.EndTileEffect(builder);
  }

  public static void StartTileEffect(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddDisplay(FlatBufferBuilder builder, Offset<Monopoly.Schema.TileEffectDisplay> displayOffset) { builder.AddOffset(0, displayOffset.Value, 0); }
  public static void AddTiming(FlatBufferBuilder builder, Monopoly.Schema.TileEffectTiming timing) { builder.AddInt(1, (int)timing, 0); }
  public static void AddExtraType(FlatBufferBuilder builder, Monopoly.Schema.TileEffectExtra extraType) { builder.AddByte(2, (byte)extraType, 0); }
  public static void AddExtra(FlatBufferBuilder builder, int extraOffset) { builder.AddOffset(3, extraOffset, 0); }
  public static Offset<Monopoly.Schema.TileEffect> EndTileEffect(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Monopoly.Schema.TileEffect>(o);
  }
};


}
