// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Monopoly.Schema
{

public enum TileEffectTiming : int
{
  UNSPECIFIED = 0,
  ENTERING = 1,
  STOPPING = 2,
  LEAVING = 3,
};


}
