// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: prisel/get_lobby_state_spec.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Prisel.Protobuf {

  /// <summary>Holder for reflection information generated from prisel/get_lobby_state_spec.proto</summary>
  public static partial class GetLobbyStateSpecReflection {

    #region Descriptor
    /// <summary>File descriptor for prisel/get_lobby_state_spec.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetLobbyStateSpecReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFwcmlzZWwvZ2V0X2xvYmJ5X3N0YXRlX3NwZWMucHJvdG8SBnByaXNlbBoW",
            "cHJpc2VsL3Jvb21faW5mby5wcm90byK3AQoVR2V0TG9iYnlTdGF0ZVJlc3Bv",
            "bnNlEj4KBXJvb21zGAEgAygLMi8ucHJpc2VsLkdldExvYmJ5U3RhdGVSZXNw",
            "b25zZS5Mb2JieVJvb21WaWV3SW5mbxpeChFMb2JieVJvb21WaWV3SW5mbxIe",
            "CgRyb29tGAEgASgLMhAucHJpc2VsLlJvb21JbmZvEhQKDHBsYXllcl9jb3Vu",
            "dBgCIAEoBRITCgttYXhfcGxheWVycxgDIAEoBUISqgIPUHJpc2VsLlByb3Rv",
            "YnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Prisel.Protobuf.RoomInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Prisel.Protobuf.GetLobbyStateResponse), global::Prisel.Protobuf.GetLobbyStateResponse.Parser, new[]{ "Rooms" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Prisel.Protobuf.GetLobbyStateResponse.Types.LobbyRoomViewInfo), global::Prisel.Protobuf.GetLobbyStateResponse.Types.LobbyRoomViewInfo.Parser, new[]{ "Room", "PlayerCount", "MaxPlayers" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// type : GET_LOBBY_STATE,
  /// packet_type : RESPONSE
  /// </summary>
  public sealed partial class GetLobbyStateResponse : pb::IMessage<GetLobbyStateResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetLobbyStateResponse> _parser = new pb::MessageParser<GetLobbyStateResponse>(() => new GetLobbyStateResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetLobbyStateResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Prisel.Protobuf.GetLobbyStateSpecReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetLobbyStateResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetLobbyStateResponse(GetLobbyStateResponse other) : this() {
      rooms_ = other.rooms_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetLobbyStateResponse Clone() {
      return new GetLobbyStateResponse(this);
    }

    /// <summary>Field number for the "rooms" field.</summary>
    public const int RoomsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Prisel.Protobuf.GetLobbyStateResponse.Types.LobbyRoomViewInfo> _repeated_rooms_codec
        = pb::FieldCodec.ForMessage(10, global::Prisel.Protobuf.GetLobbyStateResponse.Types.LobbyRoomViewInfo.Parser);
    private readonly pbc::RepeatedField<global::Prisel.Protobuf.GetLobbyStateResponse.Types.LobbyRoomViewInfo> rooms_ = new pbc::RepeatedField<global::Prisel.Protobuf.GetLobbyStateResponse.Types.LobbyRoomViewInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Prisel.Protobuf.GetLobbyStateResponse.Types.LobbyRoomViewInfo> Rooms {
      get { return rooms_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetLobbyStateResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetLobbyStateResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!rooms_.Equals(other.rooms_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= rooms_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      rooms_.WriteTo(output, _repeated_rooms_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      rooms_.WriteTo(ref output, _repeated_rooms_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += rooms_.CalculateSize(_repeated_rooms_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetLobbyStateResponse other) {
      if (other == null) {
        return;
      }
      rooms_.Add(other.rooms_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            rooms_.AddEntriesFrom(input, _repeated_rooms_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            rooms_.AddEntriesFrom(ref input, _repeated_rooms_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the GetLobbyStateResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class LobbyRoomViewInfo : pb::IMessage<LobbyRoomViewInfo>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<LobbyRoomViewInfo> _parser = new pb::MessageParser<LobbyRoomViewInfo>(() => new LobbyRoomViewInfo());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<LobbyRoomViewInfo> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Prisel.Protobuf.GetLobbyStateResponse.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public LobbyRoomViewInfo() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public LobbyRoomViewInfo(LobbyRoomViewInfo other) : this() {
          room_ = other.room_ != null ? other.room_.Clone() : null;
          playerCount_ = other.playerCount_;
          maxPlayers_ = other.maxPlayers_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public LobbyRoomViewInfo Clone() {
          return new LobbyRoomViewInfo(this);
        }

        /// <summary>Field number for the "room" field.</summary>
        public const int RoomFieldNumber = 1;
        private global::Prisel.Protobuf.RoomInfo room_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Prisel.Protobuf.RoomInfo Room {
          get { return room_; }
          set {
            room_ = value;
          }
        }

        /// <summary>Field number for the "player_count" field.</summary>
        public const int PlayerCountFieldNumber = 2;
        private int playerCount_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int PlayerCount {
          get { return playerCount_; }
          set {
            playerCount_ = value;
          }
        }

        /// <summary>Field number for the "max_players" field.</summary>
        public const int MaxPlayersFieldNumber = 3;
        private int maxPlayers_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int MaxPlayers {
          get { return maxPlayers_; }
          set {
            maxPlayers_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as LobbyRoomViewInfo);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(LobbyRoomViewInfo other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Room, other.Room)) return false;
          if (PlayerCount != other.PlayerCount) return false;
          if (MaxPlayers != other.MaxPlayers) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (room_ != null) hash ^= Room.GetHashCode();
          if (PlayerCount != 0) hash ^= PlayerCount.GetHashCode();
          if (MaxPlayers != 0) hash ^= MaxPlayers.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (room_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Room);
          }
          if (PlayerCount != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(PlayerCount);
          }
          if (MaxPlayers != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(MaxPlayers);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (room_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Room);
          }
          if (PlayerCount != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(PlayerCount);
          }
          if (MaxPlayers != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(MaxPlayers);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (room_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Room);
          }
          if (PlayerCount != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerCount);
          }
          if (MaxPlayers != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxPlayers);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(LobbyRoomViewInfo other) {
          if (other == null) {
            return;
          }
          if (other.room_ != null) {
            if (room_ == null) {
              Room = new global::Prisel.Protobuf.RoomInfo();
            }
            Room.MergeFrom(other.Room);
          }
          if (other.PlayerCount != 0) {
            PlayerCount = other.PlayerCount;
          }
          if (other.MaxPlayers != 0) {
            MaxPlayers = other.MaxPlayers;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (room_ == null) {
                  Room = new global::Prisel.Protobuf.RoomInfo();
                }
                input.ReadMessage(Room);
                break;
              }
              case 16: {
                PlayerCount = input.ReadInt32();
                break;
              }
              case 24: {
                MaxPlayers = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (room_ == null) {
                  Room = new global::Prisel.Protobuf.RoomInfo();
                }
                input.ReadMessage(Room);
                break;
              }
              case 16: {
                PlayerCount = input.ReadInt32();
                break;
              }
              case 24: {
                MaxPlayers = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
