// @generated by protobuf-ts 2.1.0 with parameter force_client_none
// @generated from protobuf file "monopoly/announce_game_over_spec.proto" (package "monopoly", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Rank } from "./rank";
/**
 * type : "announce_game_over"
 * packet_type : DEFAULT
 *
 * @generated from protobuf message monopoly.AnnounceGameOverPayload
 */
export interface AnnounceGameOverPayload {
    /**
     * @generated from protobuf field: repeated monopoly.Rank ranks = 1;
     */
    ranks: Rank[];
}
// @generated message type with reflection information, may provide speed optimized methods
class AnnounceGameOverPayload$Type extends MessageType<AnnounceGameOverPayload> {
    constructor() {
        super("monopoly.AnnounceGameOverPayload", [
            { no: 1, name: "ranks", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Rank }
        ]);
    }
    create(value?: PartialMessage<AnnounceGameOverPayload>): AnnounceGameOverPayload {
        const message = { ranks: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<AnnounceGameOverPayload>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AnnounceGameOverPayload): AnnounceGameOverPayload {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated monopoly.Rank ranks */ 1:
                    message.ranks.push(Rank.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AnnounceGameOverPayload, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated monopoly.Rank ranks = 1; */
        for (let i = 0; i < message.ranks.length; i++)
            Rank.internalBinaryWrite(message.ranks[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message monopoly.AnnounceGameOverPayload
 */
export const AnnounceGameOverPayload = new AnnounceGameOverPayload$Type();
