// @generated by protobuf-ts 2.1.0 with parameter force_client_none
// @generated from protobuf file "monopoly/announce_player_left_spec.proto" (package "monopoly", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { GamePlayer } from "./game_player";
/**
 * type : "announce_player_left"
 * packet_type : REQUEST
 *
 * @generated from protobuf message monopoly.AnnouncePlayerLeftPayload
 */
export interface AnnouncePlayerLeftPayload {
    /**
     * @generated from protobuf field: monopoly.GamePlayer player = 1;
     */
    player?: GamePlayer;
}
// @generated message type with reflection information, may provide speed optimized methods
class AnnouncePlayerLeftPayload$Type extends MessageType<AnnouncePlayerLeftPayload> {
    constructor() {
        super("monopoly.AnnouncePlayerLeftPayload", [
            { no: 1, name: "player", kind: "message", T: () => GamePlayer }
        ]);
    }
    create(value?: PartialMessage<AnnouncePlayerLeftPayload>): AnnouncePlayerLeftPayload {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<AnnouncePlayerLeftPayload>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AnnouncePlayerLeftPayload): AnnouncePlayerLeftPayload {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* monopoly.GamePlayer player */ 1:
                    message.player = GamePlayer.internalBinaryRead(reader, reader.uint32(), options, message.player);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AnnouncePlayerLeftPayload, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* monopoly.GamePlayer player = 1; */
        if (message.player)
            GamePlayer.internalBinaryWrite(message.player, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message monopoly.AnnouncePlayerLeftPayload
 */
export const AnnouncePlayerLeftPayload = new AnnouncePlayerLeftPayload$Type();
