/**
 * @file Automatically generated by barrelsby.
 */

import * as animation_spects from "./animation_spec";
import * as announce_bankrupt_spects from "./announce_bankrupt_spec";
import * as announce_end_turn_spects from "./announce_end_turn_spec";
import * as announce_game_over_spects from "./announce_game_over_spec";
import * as announce_pay_rent_spects from "./announce_pay_rent_spec";
import * as announce_player_left_spects from "./announce_player_left_spec";
import * as announce_purchase_spects from "./announce_purchase_spec";
import * as announce_received_chance_spects from "./announce_received_chance_spec";
import * as announce_roll_spects from "./announce_roll_spec";
import * as announce_start_turn_spects from "./announce_start_turn_spec";
import * as chancets from "./chance";
import * as coordinatets from "./coordinate";
import * as game_playerts from "./game_player";
import * as get_initial_state_spects from "./get_initial_state_spec";
import * as paymentts from "./payment";
import * as prompt_purchase_spects from "./prompt_purchase_spec";
import * as propertyts from "./property";
import * as rankts from "./rank";
import * as roll_spects from "./roll_spec";
export {animation_spects as animation_spec};
export {announce_bankrupt_spects as announce_bankrupt_spec};
export {announce_end_turn_spects as announce_end_turn_spec};
export {announce_game_over_spects as announce_game_over_spec};
export {announce_pay_rent_spects as announce_pay_rent_spec};
export {announce_player_left_spects as announce_player_left_spec};
export {announce_purchase_spects as announce_purchase_spec};
export {announce_received_chance_spects as announce_received_chance_spec};
export {announce_roll_spects as announce_roll_spec};
export {announce_start_turn_spects as announce_start_turn_spec};
export {chancets as chance};
export {coordinatets as coordinate};
export {game_playerts as game_player};
export {get_initial_state_spects as get_initial_state_spec};
export {paymentts as payment};
export {prompt_purchase_spects as prompt_purchase_spec};
export {propertyts as property};
export {rankts as rank};
export {roll_spects as roll_spec};
