// @generated by protobuf-ts 1.0.12 with parameters disable_service_client
// @generated from protobuf file "monopoly/move_steps_extra.proto" (package "monopoly", syntax proto3)
// tslint:disable
import { BinaryWriteOptions } from "@protobuf-ts/runtime";
import { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import { BinaryReadOptions } from "@protobuf-ts/runtime";
import { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * move a specific amount of steps forward or backward
 *
 * @generated from protobuf message monopoly.MoveStepsExtra
 */
export interface MoveStepsExtra {
    /**
     * @generated from protobuf field: int32 steps = 1;
     */
    steps: number;
}
/**
 * Type for protobuf message monopoly.MoveStepsExtra
 */
class MoveStepsExtra$Type extends MessageType<MoveStepsExtra> {
    constructor() {
        super("monopoly.MoveStepsExtra", [
            { no: 1, name: "steps", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<MoveStepsExtra>): MoveStepsExtra {
        const message = { steps: 0 };
        if (value !== undefined)
            reflectionMergePartial<MoveStepsExtra>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MoveStepsExtra): MoveStepsExtra {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 steps */ 1:
                    message.steps = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MoveStepsExtra, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 steps = 1; */
        if (message.steps !== 0)
            writer.tag(1, WireType.Varint).int32(message.steps);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
export const MoveStepsExtra = new MoveStepsExtra$Type();
