// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: monopoly/announce_roll_spec.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Monopoly.Protobuf {

  /// <summary>Holder for reflection information generated from monopoly/announce_roll_spec.proto</summary>
  public static partial class AnnounceRollSpecReflection {

    #region Descriptor
    /// <summary>File descriptor for monopoly/announce_roll_spec.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AnnounceRollSpecReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFtb25vcG9seS9hbm5vdW5jZV9yb2xsX3NwZWMucHJvdG8SCG1vbm9wb2x5",
            "Ghltb25vcG9seS9jb29yZGluYXRlLnByb3RvInYKE0Fubm91bmNlUm9sbFBh",
            "eWxvYWQSDgoGcGxheWVyGAEgASgJEg0KBXN0ZXBzGAIgASgFEi4KEGN1cnJl",
            "bnRfcG9zaXRpb24YAyABKAsyFC5tb25vcG9seS5Db29yZGluYXRlEhAKCG15",
            "X21vbmV5GAQgASgFQhSqAhFNb25vcG9seS5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Monopoly.Protobuf.CoordinateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Monopoly.Protobuf.AnnounceRollPayload), global::Monopoly.Protobuf.AnnounceRollPayload.Parser, new[]{ "Player", "Steps", "CurrentPosition", "MyMoney" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// type : "announce_roll"
  /// packet_type : DEFAULT
  /// </summary>
  public sealed partial class AnnounceRollPayload : pb::IMessage<AnnounceRollPayload>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AnnounceRollPayload> _parser = new pb::MessageParser<AnnounceRollPayload>(() => new AnnounceRollPayload());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AnnounceRollPayload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Monopoly.Protobuf.AnnounceRollSpecReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnnounceRollPayload() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnnounceRollPayload(AnnounceRollPayload other) : this() {
      player_ = other.player_;
      steps_ = other.steps_;
      currentPosition_ = other.currentPosition_ != null ? other.currentPosition_.Clone() : null;
      myMoney_ = other.myMoney_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnnounceRollPayload Clone() {
      return new AnnounceRollPayload(this);
    }

    /// <summary>Field number for the "player" field.</summary>
    public const int PlayerFieldNumber = 1;
    private string player_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Player {
      get { return player_; }
      set {
        player_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "steps" field.</summary>
    public const int StepsFieldNumber = 2;
    private int steps_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Steps {
      get { return steps_; }
      set {
        steps_ = value;
      }
    }

    /// <summary>Field number for the "current_position" field.</summary>
    public const int CurrentPositionFieldNumber = 3;
    private global::Monopoly.Protobuf.Coordinate currentPosition_;
    /// <summary>
    /// the position of the player before moving. This is used to make sure the
    /// rendering of the player is in sync on all clients.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Monopoly.Protobuf.Coordinate CurrentPosition {
      get { return currentPosition_; }
      set {
        currentPosition_ = value;
      }
    }

    /// <summary>Field number for the "my_money" field.</summary>
    public const int MyMoneyFieldNumber = 4;
    private int myMoney_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MyMoney {
      get { return myMoney_; }
      set {
        myMoney_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AnnounceRollPayload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AnnounceRollPayload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Player != other.Player) return false;
      if (Steps != other.Steps) return false;
      if (!object.Equals(CurrentPosition, other.CurrentPosition)) return false;
      if (MyMoney != other.MyMoney) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Player.Length != 0) hash ^= Player.GetHashCode();
      if (Steps != 0) hash ^= Steps.GetHashCode();
      if (currentPosition_ != null) hash ^= CurrentPosition.GetHashCode();
      if (MyMoney != 0) hash ^= MyMoney.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Player.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Player);
      }
      if (Steps != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Steps);
      }
      if (currentPosition_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CurrentPosition);
      }
      if (MyMoney != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(MyMoney);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Player.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Player);
      }
      if (Steps != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Steps);
      }
      if (currentPosition_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CurrentPosition);
      }
      if (MyMoney != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(MyMoney);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Player.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Player);
      }
      if (Steps != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Steps);
      }
      if (currentPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrentPosition);
      }
      if (MyMoney != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MyMoney);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AnnounceRollPayload other) {
      if (other == null) {
        return;
      }
      if (other.Player.Length != 0) {
        Player = other.Player;
      }
      if (other.Steps != 0) {
        Steps = other.Steps;
      }
      if (other.currentPosition_ != null) {
        if (currentPosition_ == null) {
          CurrentPosition = new global::Monopoly.Protobuf.Coordinate();
        }
        CurrentPosition.MergeFrom(other.CurrentPosition);
      }
      if (other.MyMoney != 0) {
        MyMoney = other.MyMoney;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Player = input.ReadString();
            break;
          }
          case 16: {
            Steps = input.ReadInt32();
            break;
          }
          case 26: {
            if (currentPosition_ == null) {
              CurrentPosition = new global::Monopoly.Protobuf.Coordinate();
            }
            input.ReadMessage(CurrentPosition);
            break;
          }
          case 32: {
            MyMoney = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Player = input.ReadString();
            break;
          }
          case 16: {
            Steps = input.ReadInt32();
            break;
          }
          case 26: {
            if (currentPosition_ == null) {
              CurrentPosition = new global::Monopoly.Protobuf.Coordinate();
            }
            input.ReadMessage(CurrentPosition);
            break;
          }
          case 32: {
            MyMoney = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
