// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: monopoly/prompt_purchase_spec.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Monopoly.Protobuf {

  /// <summary>Holder for reflection information generated from monopoly/prompt_purchase_spec.proto</summary>
  public static partial class PromptPurchaseSpecReflection {

    #region Descriptor
    /// <summary>File descriptor for monopoly/prompt_purchase_spec.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PromptPurchaseSpecReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNtb25vcG9seS9wcm9tcHRfcHVyY2hhc2Vfc3BlYy5wcm90bxIIbW9ub3Bv",
            "bHkaF21vbm9wb2x5L3Byb3BlcnR5LnByb3RvIpwBChVQcm9tcHRQdXJjaGFz",
            "ZVJlcXVlc3QSKAoIcHJvcGVydHkYASABKAsyFi5tb25vcG9seS5Qcm9wZXJ0",
            "eUluZm8SJwoGbGV2ZWxzGAIgAygLMhcubW9ub3BvbHkuUHJvcGVydHlMZXZl",
            "bBISCgppc191cGdyYWRlGAcgASgIEhwKFG1vbmV5X2FmdGVyX3B1cmNoYXNl",
            "GAggASgFIisKFlByb21wdFB1cmNoYXNlUmVzcG9uc2USEQoJcHVyY2hhc2Vk",
            "GAEgASgIQhSqAhFNb25vcG9seS5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Monopoly.Protobuf.PropertyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Monopoly.Protobuf.PromptPurchaseRequest), global::Monopoly.Protobuf.PromptPurchaseRequest.Parser, new[]{ "Property", "Levels", "IsUpgrade", "MoneyAfterPurchase" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Monopoly.Protobuf.PromptPurchaseResponse), global::Monopoly.Protobuf.PromptPurchaseResponse.Parser, new[]{ "Purchased" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// type : "prompt_purchase"
  /// packet_type : REQUEST
  /// </summary>
  public sealed partial class PromptPurchaseRequest : pb::IMessage<PromptPurchaseRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PromptPurchaseRequest> _parser = new pb::MessageParser<PromptPurchaseRequest>(() => new PromptPurchaseRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PromptPurchaseRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Monopoly.Protobuf.PromptPurchaseSpecReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PromptPurchaseRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PromptPurchaseRequest(PromptPurchaseRequest other) : this() {
      property_ = other.property_ != null ? other.property_.Clone() : null;
      levels_ = other.levels_.Clone();
      isUpgrade_ = other.isUpgrade_;
      moneyAfterPurchase_ = other.moneyAfterPurchase_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PromptPurchaseRequest Clone() {
      return new PromptPurchaseRequest(this);
    }

    /// <summary>Field number for the "property" field.</summary>
    public const int PropertyFieldNumber = 1;
    private global::Monopoly.Protobuf.PropertyInfo property_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Monopoly.Protobuf.PropertyInfo Property {
      get { return property_; }
      set {
        property_ = value;
      }
    }

    /// <summary>Field number for the "levels" field.</summary>
    public const int LevelsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Monopoly.Protobuf.PropertyLevel> _repeated_levels_codec
        = pb::FieldCodec.ForMessage(18, global::Monopoly.Protobuf.PropertyLevel.Parser);
    private readonly pbc::RepeatedField<global::Monopoly.Protobuf.PropertyLevel> levels_ = new pbc::RepeatedField<global::Monopoly.Protobuf.PropertyLevel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Monopoly.Protobuf.PropertyLevel> Levels {
      get { return levels_; }
    }

    /// <summary>Field number for the "is_upgrade" field.</summary>
    public const int IsUpgradeFieldNumber = 7;
    private bool isUpgrade_;
    /// <summary>
    /// Whether this property can be upgraded right now. Only purchased
    /// land/property that has not reached the upgrade limit can be upgraded.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsUpgrade {
      get { return isUpgrade_; }
      set {
        isUpgrade_ = value;
      }
    }

    /// <summary>Field number for the "money_after_purchase" field.</summary>
    public const int MoneyAfterPurchaseFieldNumber = 8;
    private int moneyAfterPurchase_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MoneyAfterPurchase {
      get { return moneyAfterPurchase_; }
      set {
        moneyAfterPurchase_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PromptPurchaseRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PromptPurchaseRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Property, other.Property)) return false;
      if(!levels_.Equals(other.levels_)) return false;
      if (IsUpgrade != other.IsUpgrade) return false;
      if (MoneyAfterPurchase != other.MoneyAfterPurchase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (property_ != null) hash ^= Property.GetHashCode();
      hash ^= levels_.GetHashCode();
      if (IsUpgrade != false) hash ^= IsUpgrade.GetHashCode();
      if (MoneyAfterPurchase != 0) hash ^= MoneyAfterPurchase.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (property_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Property);
      }
      levels_.WriteTo(output, _repeated_levels_codec);
      if (IsUpgrade != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsUpgrade);
      }
      if (MoneyAfterPurchase != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(MoneyAfterPurchase);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (property_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Property);
      }
      levels_.WriteTo(ref output, _repeated_levels_codec);
      if (IsUpgrade != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsUpgrade);
      }
      if (MoneyAfterPurchase != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(MoneyAfterPurchase);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (property_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Property);
      }
      size += levels_.CalculateSize(_repeated_levels_codec);
      if (IsUpgrade != false) {
        size += 1 + 1;
      }
      if (MoneyAfterPurchase != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MoneyAfterPurchase);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PromptPurchaseRequest other) {
      if (other == null) {
        return;
      }
      if (other.property_ != null) {
        if (property_ == null) {
          Property = new global::Monopoly.Protobuf.PropertyInfo();
        }
        Property.MergeFrom(other.Property);
      }
      levels_.Add(other.levels_);
      if (other.IsUpgrade != false) {
        IsUpgrade = other.IsUpgrade;
      }
      if (other.MoneyAfterPurchase != 0) {
        MoneyAfterPurchase = other.MoneyAfterPurchase;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (property_ == null) {
              Property = new global::Monopoly.Protobuf.PropertyInfo();
            }
            input.ReadMessage(Property);
            break;
          }
          case 18: {
            levels_.AddEntriesFrom(input, _repeated_levels_codec);
            break;
          }
          case 56: {
            IsUpgrade = input.ReadBool();
            break;
          }
          case 64: {
            MoneyAfterPurchase = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (property_ == null) {
              Property = new global::Monopoly.Protobuf.PropertyInfo();
            }
            input.ReadMessage(Property);
            break;
          }
          case 18: {
            levels_.AddEntriesFrom(ref input, _repeated_levels_codec);
            break;
          }
          case 56: {
            IsUpgrade = input.ReadBool();
            break;
          }
          case 64: {
            MoneyAfterPurchase = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// type : "prompt_purchase"
  /// packet_type : REQUEST
  /// </summary>
  public sealed partial class PromptPurchaseResponse : pb::IMessage<PromptPurchaseResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PromptPurchaseResponse> _parser = new pb::MessageParser<PromptPurchaseResponse>(() => new PromptPurchaseResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PromptPurchaseResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Monopoly.Protobuf.PromptPurchaseSpecReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PromptPurchaseResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PromptPurchaseResponse(PromptPurchaseResponse other) : this() {
      purchased_ = other.purchased_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PromptPurchaseResponse Clone() {
      return new PromptPurchaseResponse(this);
    }

    /// <summary>Field number for the "purchased" field.</summary>
    public const int PurchasedFieldNumber = 1;
    private bool purchased_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Purchased {
      get { return purchased_; }
      set {
        purchased_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PromptPurchaseResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PromptPurchaseResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Purchased != other.Purchased) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Purchased != false) hash ^= Purchased.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Purchased != false) {
        output.WriteRawTag(8);
        output.WriteBool(Purchased);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Purchased != false) {
        output.WriteRawTag(8);
        output.WriteBool(Purchased);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Purchased != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PromptPurchaseResponse other) {
      if (other == null) {
        return;
      }
      if (other.Purchased != false) {
        Purchased = other.Purchased;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Purchased = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Purchased = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
