import typescript from 'rollup-plugin-typescript2';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';

import pkg from './package.json';

const externalDependencyList = [...Object.keys(pkg.dependencies)];

export default [
    // browser-friendly UMD build
    {
        input: 'index.ts',
        output: {
            name: 'priselCommon',
            file: pkg.browser,
            format: 'umd',
        },
        plugins: [
            resolve({
                // This is a browser module, should not use any node internal.
                preferBuiltins: false,
            }), // so Rollup can find dependencies
            commonjs(), // so Rollup can convert dependencies to an ES module
            typescript({
                tsconfigOverride: {
                    compilerOptions: {
                        // due to https://github.com/ezolenko/rollup-plugin-typescript2/issues/24
                        // interface type declaration are not generated by rollup.
                        // we will call tsc to generate the declaration files in the same build directory
                        declaration: false,
                    },
                },
            }), // so Rollup can convert TypeScript to JavaScript
        ],
    },

    // CommonJS (for Node) and ES module (for bundlers) build.
    // (We could have three entries in the configuration array
    // instead of two, but it's quicker to generate multiple
    // builds from a single configuration where possible, using
    // an array for the `output` option, where we can specify
    // `file` and `format` for each target)
    {
        input: 'index.ts',
        external: (id) =>
            externalDependencyList.some((dep) => id === dep || id.startsWith(`${dep}/`)),
        plugins: [
            typescript({
                tsconfigOverride: {
                    compilerOptions: {
                        // due to https://github.com/ezolenko/rollup-plugin-typescript2/issues/24
                        // interface type declaration are not generated by rollup.
                        // we will call tsc to generate the declaration files in the same build directory
                        declaration: false,
                    },
                },
            }), // so Rollup can convert TypeScript to JavaScript
        ],
        output: [
            { file: pkg.main, format: 'cjs' },
            { file: pkg.module, format: 'es' },
        ],
    },

    {
        input: 'actionConfigs.ts',
        plugins: [
            typescript({
                compilerOptions: {
                    declaration: false,
                },
            }), // so Rollup can convert TypeScript to JavaScript
        ],
        output: [{ file: './lib/actionConfigs.cjs.js', format: 'cjs' }],
    },
];
