// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Prisel.Common
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct GetRoomStateResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static GetRoomStateResponse GetRootAsGetRoomStateResponse(ByteBuffer _bb) { return GetRootAsGetRoomStateResponse(_bb, new GetRoomStateResponse()); }
  public static GetRoomStateResponse GetRootAsGetRoomStateResponse(ByteBuffer _bb, GetRoomStateResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetRoomStateResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Prisel.Common.RoomStateSnapshot? RoomState { get { int o = __p.__offset(4); return o != 0 ? (Prisel.Common.RoomStateSnapshot?)(new Prisel.Common.RoomStateSnapshot()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Prisel.Common.GetRoomStateResponse> CreateGetRoomStateResponse(FlatBufferBuilder builder,
      Offset<Prisel.Common.RoomStateSnapshot> room_stateOffset = default(Offset<Prisel.Common.RoomStateSnapshot>)) {
    builder.StartTable(1);
    GetRoomStateResponse.AddRoomState(builder, room_stateOffset);
    return GetRoomStateResponse.EndGetRoomStateResponse(builder);
  }

  public static void StartGetRoomStateResponse(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddRoomState(FlatBufferBuilder builder, Offset<Prisel.Common.RoomStateSnapshot> roomStateOffset) { builder.AddOffset(0, roomStateOffset.Value, 0); }
  public static Offset<Prisel.Common.GetRoomStateResponse> EndGetRoomStateResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Prisel.Common.GetRoomStateResponse>(o);
  }
};


}
