// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Prisel.Common
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct LobbyRoomViewInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static LobbyRoomViewInfo GetRootAsLobbyRoomViewInfo(ByteBuffer _bb) { return GetRootAsLobbyRoomViewInfo(_bb, new LobbyRoomViewInfo()); }
  public static LobbyRoomViewInfo GetRootAsLobbyRoomViewInfo(ByteBuffer _bb, LobbyRoomViewInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LobbyRoomViewInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Prisel.Common.RoomInfo? Room { get { int o = __p.__offset(4); return o != 0 ? (Prisel.Common.RoomInfo?)(new Prisel.Common.RoomInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public int PlayerCount { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxPlayers { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Prisel.Common.LobbyRoomViewInfo> CreateLobbyRoomViewInfo(FlatBufferBuilder builder,
      Offset<Prisel.Common.RoomInfo> roomOffset = default(Offset<Prisel.Common.RoomInfo>),
      int player_count = 0,
      int max_players = 0) {
    builder.StartTable(3);
    LobbyRoomViewInfo.AddMaxPlayers(builder, max_players);
    LobbyRoomViewInfo.AddPlayerCount(builder, player_count);
    LobbyRoomViewInfo.AddRoom(builder, roomOffset);
    return LobbyRoomViewInfo.EndLobbyRoomViewInfo(builder);
  }

  public static void StartLobbyRoomViewInfo(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddRoom(FlatBufferBuilder builder, Offset<Prisel.Common.RoomInfo> roomOffset) { builder.AddOffset(0, roomOffset.Value, 0); }
  public static void AddPlayerCount(FlatBufferBuilder builder, int playerCount) { builder.AddInt(1, playerCount, 0); }
  public static void AddMaxPlayers(FlatBufferBuilder builder, int maxPlayers) { builder.AddInt(2, maxPlayers, 0); }
  public static Offset<Prisel.Common.LobbyRoomViewInfo> EndLobbyRoomViewInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Prisel.Common.LobbyRoomViewInfo>(o);
  }
};


}
