// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Prisel.Common
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct LoginRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static LoginRequest GetRootAsLoginRequest(ByteBuffer _bb) { return GetRootAsLoginRequest(_bb, new LoginRequest()); }
  public static LoginRequest GetRootAsLoginRequest(ByteBuffer _bb, LoginRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LoginRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Username { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUsernameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUsernameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUsernameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Prisel.Common.LoginRequest> CreateLoginRequest(FlatBufferBuilder builder,
      StringOffset usernameOffset = default(StringOffset)) {
    builder.StartTable(1);
    LoginRequest.AddUsername(builder, usernameOffset);
    return LoginRequest.EndLoginRequest(builder);
  }

  public static void StartLoginRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddUsername(FlatBufferBuilder builder, StringOffset usernameOffset) { builder.AddOffset(0, usernameOffset.Value, 0); }
  public static Offset<Prisel.Common.LoginRequest> EndLoginRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Prisel.Common.LoginRequest>(o);
  }
};


}
