// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Prisel.Common
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct PlayerJoinInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static PlayerJoinInfo GetRootAsPlayerJoinInfo(ByteBuffer _bb) { return GetRootAsPlayerJoinInfo(_bb, new PlayerJoinInfo()); }
  public static PlayerJoinInfo GetRootAsPlayerJoinInfo(ByteBuffer _bb, PlayerJoinInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerJoinInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Prisel.Common.PlayerInfo? Player { get { int o = __p.__offset(4); return o != 0 ? (Prisel.Common.PlayerInfo?)(new Prisel.Common.PlayerInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Prisel.Common.PlayerJoinInfo> CreatePlayerJoinInfo(FlatBufferBuilder builder,
      Offset<Prisel.Common.PlayerInfo> playerOffset = default(Offset<Prisel.Common.PlayerInfo>)) {
    builder.StartTable(1);
    PlayerJoinInfo.AddPlayer(builder, playerOffset);
    return PlayerJoinInfo.EndPlayerJoinInfo(builder);
  }

  public static void StartPlayerJoinInfo(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPlayer(FlatBufferBuilder builder, Offset<Prisel.Common.PlayerInfo> playerOffset) { builder.AddOffset(0, playerOffset.Value, 0); }
  public static Offset<Prisel.Common.PlayerJoinInfo> EndPlayerJoinInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Prisel.Common.PlayerJoinInfo>(o);
  }
};


}
