// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Prisel.Common
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct RoomStateChangePayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static RoomStateChangePayload GetRootAsRoomStateChangePayload(ByteBuffer _bb) { return GetRootAsRoomStateChangePayload(_bb, new RoomStateChangePayload()); }
  public static RoomStateChangePayload GetRootAsRoomStateChangePayload(ByteBuffer _bb, RoomStateChangePayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RoomStateChangePayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Prisel.Common.RoomStateChangeInfo ChangeType { get { int o = __p.__offset(4); return o != 0 ? (Prisel.Common.RoomStateChangeInfo)__p.bb.Get(o + __p.bb_pos) : Prisel.Common.RoomStateChangeInfo.NONE; } }
  public TTable? Change<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public Prisel.Common.PlayerJoinInfo ChangeAsPlayerJoinInfo() { return Change<Prisel.Common.PlayerJoinInfo>().Value; }
  public Prisel.Common.PlayerLeaveInfo ChangeAsPlayerLeaveInfo() { return Change<Prisel.Common.PlayerLeaveInfo>().Value; }
  public Prisel.Common.HostLeaveInfo ChangeAsHostLeaveInfo() { return Change<Prisel.Common.HostLeaveInfo>().Value; }
  public Prisel.Common.UpdateToken? Token { get { int o = __p.__offset(8); return o != 0 ? (Prisel.Common.UpdateToken?)(new Prisel.Common.UpdateToken()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Prisel.Common.RoomStateChangePayload> CreateRoomStateChangePayload(FlatBufferBuilder builder,
      Prisel.Common.RoomStateChangeInfo change_type = Prisel.Common.RoomStateChangeInfo.NONE,
      int changeOffset = 0,
      Offset<Prisel.Common.UpdateToken> tokenOffset = default(Offset<Prisel.Common.UpdateToken>)) {
    builder.StartTable(3);
    RoomStateChangePayload.AddToken(builder, tokenOffset);
    RoomStateChangePayload.AddChange(builder, changeOffset);
    RoomStateChangePayload.AddChangeType(builder, change_type);
    return RoomStateChangePayload.EndRoomStateChangePayload(builder);
  }

  public static void StartRoomStateChangePayload(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddChangeType(FlatBufferBuilder builder, Prisel.Common.RoomStateChangeInfo changeType) { builder.AddByte(0, (byte)changeType, 0); }
  public static void AddChange(FlatBufferBuilder builder, int changeOffset) { builder.AddOffset(1, changeOffset, 0); }
  public static void AddToken(FlatBufferBuilder builder, Offset<Prisel.Common.UpdateToken> tokenOffset) { builder.AddOffset(2, tokenOffset.Value, 0); }
  public static Offset<Prisel.Common.RoomStateChangePayload> EndRoomStateChangePayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Prisel.Common.RoomStateChangePayload>(o);
  }
};


}
