// @generated by protobuf-ts 1.0.12 with parameters disable_service_client
// @generated from protobuf file "prisel/system_action_type.proto" (package "prisel", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum prisel.SystemActionType
 */
export enum SystemActionType {
    /**
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: WELCOME = 1;
     */
    WELCOME = 1,
    /**
     * @generated from protobuf enum value: LOGIN = 2;
     */
    LOGIN = 2,
    /**
     * @generated from protobuf enum value: JOIN = 3;
     */
    JOIN = 3,
    /**
     * @generated from protobuf enum value: CREATE_ROOM = 4;
     */
    CREATE_ROOM = 4,
    /**
     * @generated from protobuf enum value: LEAVE = 5;
     */
    LEAVE = 5,
    /**
     * @generated from protobuf enum value: EXIT = 6;
     */
    EXIT = 6,
    /**
     * @generated from protobuf enum value: GAME_START = 7;
     */
    GAME_START = 7,
    /**
     * @generated from protobuf enum value: CHAT = 8;
     */
    CHAT = 8,
    /**
     * @generated from protobuf enum value: BROADCAST = 9;
     */
    BROADCAST = 9,
    /**
     * @generated from protobuf enum value: ROOM_STATE_CHANGE = 10;
     */
    ROOM_STATE_CHANGE = 10,
    /**
     * @generated from protobuf enum value: ANNOUNCE_GAME_START = 11;
     */
    ANNOUNCE_GAME_START = 11,
    /**
     * @generated from protobuf enum value: ERROR = 12;
     */
    ERROR = 12,
    /**
     * @generated from protobuf enum value: GET_ROOM_STATE = 13;
     */
    GET_ROOM_STATE = 13,
    /**
     * @generated from protobuf enum value: GET_LOBBY_STATE = 14;
     */
    GET_LOBBY_STATE = 14
}
