// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class JoinRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):JoinRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsJoinRequest(bb:flatbuffers.ByteBuffer, obj?:JoinRequest):JoinRequest {
  return (obj || new JoinRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsJoinRequest(bb:flatbuffers.ByteBuffer, obj?:JoinRequest):JoinRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new JoinRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

roomId():string|null
roomId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
roomId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startJoinRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRoomId(builder:flatbuffers.Builder, roomIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, roomIdOffset, 0);
}

static endJoinRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createJoinRequest(builder:flatbuffers.Builder, roomIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  JoinRequest.startJoinRequest(builder);
  JoinRequest.addRoomId(builder, roomIdOffset);
  return JoinRequest.endJoinRequest(builder);
}
}
