// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class LoginResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):LoginResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLoginResponse(bb:flatbuffers.ByteBuffer, obj?:LoginResponse):LoginResponse {
  return (obj || new LoginResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLoginResponse(bb:flatbuffers.ByteBuffer, obj?:LoginResponse):LoginResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LoginResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

userId():string|null
userId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
userId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startLoginResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addUserId(builder:flatbuffers.Builder, userIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, userIdOffset, 0);
}

static endLoginResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLoginResponse(builder:flatbuffers.Builder, userIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  LoginResponse.startLoginResponse(builder);
  LoginResponse.addUserId(builder, userIdOffset);
  return LoginResponse.endLoginResponse(builder);
}
}
