// automatically generated by the FlatBuffers compiler, do not modify

import { HostLeaveInfo } from '../../prisel/common/host-leave-info';
import { PlayerJoinInfo } from '../../prisel/common/player-join-info';
import { PlayerLeaveInfo } from '../../prisel/common/player-leave-info';


export enum RoomStateChangeInfo{
  NONE = 0,
  PlayerJoinInfo = 1,
  PlayerLeaveInfo = 2,
  HostLeaveInfo = 3
}

export function unionToRoomStateChangeInfo(
  type: RoomStateChangeInfo,
  accessor: (obj:HostLeaveInfo|PlayerJoinInfo|PlayerLeaveInfo) => HostLeaveInfo|PlayerJoinInfo|PlayerLeaveInfo|null
): HostLeaveInfo|PlayerJoinInfo|PlayerLeaveInfo|null {
  switch(RoomStateChangeInfo[type]) {
    case 'NONE': return null; 
    case 'PlayerJoinInfo': return accessor(new PlayerJoinInfo())! as PlayerJoinInfo;
    case 'PlayerLeaveInfo': return accessor(new PlayerLeaveInfo())! as PlayerLeaveInfo;
    case 'HostLeaveInfo': return accessor(new HostLeaveInfo())! as HostLeaveInfo;
    default: return null;
  }
}

export function unionListToRoomStateChangeInfo(
  type: RoomStateChangeInfo, 
  accessor: (index: number, obj:HostLeaveInfo|PlayerJoinInfo|PlayerLeaveInfo) => HostLeaveInfo|PlayerJoinInfo|PlayerLeaveInfo|null, 
  index: number
): HostLeaveInfo|PlayerJoinInfo|PlayerLeaveInfo|null {
  switch(RoomStateChangeInfo[type]) {
    case 'NONE': return null; 
    case 'PlayerJoinInfo': return accessor(index, new PlayerJoinInfo())! as PlayerJoinInfo;
    case 'PlayerLeaveInfo': return accessor(index, new PlayerLeaveInfo())! as PlayerLeaveInfo;
    case 'HostLeaveInfo': return accessor(index, new HostLeaveInfo())! as HostLeaveInfo;
    default: return null;
  }
}

