declare const styles: {
  readonly "token": string;
  readonly "comment": string;
  readonly "prolog": string;
  readonly "doctype": string;
  readonly "cdata": string;
  readonly "punctuation": string;
  readonly "namespace": string;
  readonly "property": string;
  readonly "tag": string;
  readonly "boolean": string;
  readonly "number": string;
  readonly "constant": string;
  readonly "symbol": string;
  readonly "deleted": string;
  readonly "selector": string;
  readonly "attr-name": string;
  readonly "string": string;
  readonly "char": string;
  readonly "builtin": string;
  readonly "inserted": string;
  readonly "operator": string;
  readonly "entity": string;
  readonly "url": string;
  readonly "language-css": string;
  readonly "style": string;
  readonly "atrule": string;
  readonly "attr-value": string;
  readonly "keyword": string;
  readonly "function": string;
  readonly "regex": string;
  readonly "important": string;
  readonly "variable": string;
  readonly "bold": string;
  readonly "italic": string;
};
export = styles;

