import resolve from 'rollup-plugin-node-resolve';
import typescript from 'rollup-plugin-typescript2';
import pkg from './package.json';

const externalDependencyList = [...Object.keys(pkg.dependencies), 'react', 'react-dom'];

// Deprecated
export default [
    {
        input: 'index.ts',
        output: [{ file: pkg.main, format: 'cjs' }, { file: pkg.module, format: 'es' }],
        external: (id) =>
            externalDependencyList.some((dep) => id === dep || id.startsWith(`${dep}/`)),
        plugins: [
            resolve({
                // need to specify preferBuiltins
                // https://github.com/rollup/rollup-plugin-node-resolve/issues/196
                preferBuiltins: true,
            }), // so Rollup can find dependencies
            typescript({
                tsconfigOverride: {
                    compilerOptions: {
                        // due to https://github.com/ezolenko/rollup-plugin-typescript2/issues/24
                        // interface type declaration are not generated by rollup.
                        // we will call tsc to generate the declaration files in the same build directory
                        declaration: false,
                    },
                },
            }), // so Rollup can convert TypeScript to JavaScript
        ],
    },
];
