// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { GamePlayer } from '../../monopoly/schema/game-player';


export class GetInitialStateResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):GetInitialStateResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetInitialStateResponse(bb:flatbuffers.ByteBuffer, obj?:GetInitialStateResponse):GetInitialStateResponse {
  return (obj || new GetInitialStateResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetInitialStateResponse(bb:flatbuffers.ByteBuffer, obj?:GetInitialStateResponse):GetInitialStateResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetInitialStateResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

players(index: number, obj?:GamePlayer):GamePlayer|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new GamePlayer()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

playersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

firstPlayerId():string|null
firstPlayerId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
firstPlayerId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startGetInitialStateResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPlayers(builder:flatbuffers.Builder, playersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, playersOffset, 0);
}

static createPlayersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPlayersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addFirstPlayerId(builder:flatbuffers.Builder, firstPlayerIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, firstPlayerIdOffset, 0);
}

static endGetInitialStateResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetInitialStateResponse(builder:flatbuffers.Builder, playersOffset:flatbuffers.Offset, firstPlayerIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetInitialStateResponse.startGetInitialStateResponse(builder);
  GetInitialStateResponse.addPlayers(builder, playersOffset);
  GetInitialStateResponse.addFirstPlayerId(builder, firstPlayerIdOffset);
  return GetInitialStateResponse.endGetInitialStateResponse(builder);
}
}
